- commands/WebhookCommands.js
use the value from the file when not provided on the commandline
> fixing #17

- commands/WebhookCommands.js
From: https://github.com/spark/spark-cli/pull/197
> Remove # from webhook list

- commands/KeyCommands.js
> fix missing rename for saveKeyFromCore and writeKeyToCore

- CHANGELOG.md
- README.md
- mappings.json
- updated compile commands
- bring changelog up to latest version
> Updated Readme and Changelog

- commands/FlashCommand.js
- lib/deviceSpecs.js
- lib/dfu.js
- settings.js
- checks against `deviceSpecs` for a list of known App based on the device type
- updated `settings.js` to fix append file path to binary
- added function to verify the knownApp passed from cmdline
> retrieve knownApp based on DFU device

- lib/deviceSpecs/index.js
- lib/deviceSpecs/specifications.js
- settings.js
Issue is from the unresolved path for the binary location.
- Path fixing function moved to settings.js
- remove "binaries/" path from specfications.js to prevent path checking issues from slipping through.
- clean up deviceSpecs index.js for now
> Fix knownApps flashing issue

- lib/dfu.js
> removed unused defer()

- .travis.yml
`.travis.yml` file setup to run CI test automatically with each new PR/commit.
> Move tests to master

- commands/PublishCommand.js
- lib/ApiClient.js
- defaults to private for publishing
- Fixes: https://github.com/spark/particle-cli/issues/132
- This should not be merged in until i write up some docs and confirm the syntax with @nexxy
> Added --public flag for publish

- commands/CloudCommands.js
> compile: support duo

- commands/CloudCommands.js
- lib/ApiClient.js
- package.json
- Update form-data module to pass the subdirectory information to the API
- Recursively traverse source directories
- Include the base name for all source files to be compiled
> Compile files in subdirectories

- README.md
fixes issue https://github.com/spark/particle-cli/issues/204
> Documents --target and updates possible compile platforms documentation.

- src/cli/index.js
- src/cli/project.js
- src/cli/project_init.js
project initialization command
> project init command

- README.md
- reordered the webhook commands to suit newcomers
- docs for #205 
- spark/docs PR here: https://github.com/spark/docs/pull/550
> docs: webhook delete all

- commands/WirelessCommand/connect/executor.js
- commands/WirelessCommand/connect/windows.js
- package.json
- test/oldcmd/WirelessCommand/connect/windows.spec.js
these changes were still uncommitted
> mostly refactoring

- src/lib/dfu.js
Fixed broken reference to udev file.
> fixed udev rules file reference

- src/cmd/wireless.js
Fixes https://github.com/particle-iot/particle-cli/issues/378 - this issue seems to be caused by a change in the dependency SoftAP - the function `eapTypeValue` was changed from a static function to a prototype function.
> Fix incorrect usage of SoftAP

- src/cli/index.js
- src/cli/update-cli.js
- src/cmd/update-cli.js
> Document the update-cli command

- .travis.yml
- package.json
- test/cmd/function.spec.js
> Fail Travis build when a Mocha test with --only is checked in

- package-lock.json
- package.json
Later versions of serialport are not precompiled for Windows
> Pin serialport to 6.2.0

- package-lock.json
- package.json
- src/cmd/binary.js
- test/integration/library_init.integration.js
Story details: https://app.clubhouse.io/particle/story/26329
TODO
> Update binary-version-reader to support Gen 3 bootloader and NCP

- .idea/workspace.xml
- package-lock.json
- src/cmd/flash.js
- src/cmd/serial.js
Hi,
Not being able to do an unintended install/upgrade to 1.0.0 is a PITA. This makes the bootloader update via particle flash serial work fine.
Previously signed CLA in '16
> added --yes for particle flash serial to remove blue light prompt

- package-lock.json
- package.json
Story details: https://app.clubhouse.io/particle/story/31234
> Support SOMs in binary version reader in CLI

- npm-shrinkwrap.json
- package.json
- src/cmd/usb.js
https://github.com/particle-iot/particle-usb/pull/12
Again, see https://github.com/particle-iot/particle-usb/pull/12 :smile:
For CLI specifically the only change required is to disable filtering of devices in DFU mode.
1. ~Modify `package.json` to point to a local `particle-usb` repository pointing to https://github.com/particle-iot/particle-usb/pull/12~
2. `npm install`
3. `node dist/index.js usb reset XXXXXXXXXXXX`
- [CH31926]
- https://github.com/particle-iot/particle-usb/pull/12
> usb: particle usb reset for devices in DFU mode

- src/lib/utilities.js
I was running version `1.44.0` of `particle-cli` and noticed that I was no longer able to successfully run `particle compile`. I kept getting the following error message.
I look into the codebase and noticed that the `arrayToHashSet` function was missing. I checked the git history and noticed that the function was present in version `1.43.3`. I took the function from that release and just added it to the master branch.
> Re-added the arrayToHashset function

- src/cli/token.js
- src/cmd/token.js
- src/lib/api-client.js
- test/e2e/token.e2e.js
Story details: https://app.clubhouse.io/particle/story/40383
> Add expiration time parameter to CLI token creation

- npm-shrinkwrap.json
- package.json
- test/e2e/preprocess.e2e.js
Story details: https://app.clubhouse.io/particle/story/31356
> Include Particle.h in preprocessed cpp file

- src/cmd/serial.js
- test/e2e/serial.e2e.js
Story details: https://app.clubhouse.io/particle/story/48848
> Create PoC of adding Device ID to the output of serial list

- src/lib/api-client.js
- test/e2e/compile.e2e.js
Story details: https://app.clubhouse.io/particle/story/52181
Another bug because of Core platform_id 0 :(
> Compilation broken for Core

- src/cli/subscribe.js
- src/cmd/subscribe.js
- test/e2e/subscribe.e2e.js
Story details: https://app.clubhouse.io/particle/story/51708
I held off on writing tests for this. I know there is other work in progress that may provide a similar solution internal to the CLI.
> Exit CLI after receiving matching event data or a max number of events

- .travis.yml
- src/app/command-processor.js
- src/cli/keys.js
- src/cli/keys.test.js
- src/cmd/keys.js
- src/cmd/keys.test.js
- test/e2e/get.e2e.js
- test/e2e/keys.e2e.js
- test/e2e/variable.e2e.js
Story details: https://app.clubhouse.io/particle/story/48657
> Add option to server keys command that creates formatted key files without a device being connected

- src/app/prompts.js
- src/lib/prompts.js
Story details: https://app.clubhouse.io/particle/story/57208
> Professionalize "No email" message in CLI

- npm-shrinkwrap.json
- package.json
Story details: https://app.shortcut.com/particle/story/118327
Update particle-library-manager to include https://github.com/particle-iot/particle-library-manager/pull/32 in order to fix library upload.
Steps to test
> fix: [sc-118327] Library upload broken

- src/cmd/binary.js
> Minor clean up

- src/cmd/base.js
- src/cmd/cloud.js
- src/cmd/cloud.test.js
- src/cmd/flash.js
- test/e2e/compile.e2e.js
Story details: https://app.shortcut.com/particle/story/120185
This PR changes the behavior of the `particle flash` over cloud command. It will send the source code to the compile endpoint, then download the binary if compilation is successful, then bundle if necessary then flash.
**Before:**
```
Compiling code for photon
Including:
blink.ino
attempting to compile firmware
downloading binary from: /v1/binaries/64aed053eebfcadb80c5e69e
saving to: photon_firmware_1689178191864.bin
Memory use:
text	   data	    bss	    dec	    hex	filename
4188	    112	   1400	   5700	   1644	/workspace/target/workspace.elf
Compile succeeded.
Saved firmware to: /blink/photon_firmware_1689178191864.bin
```
**After:**
```
Compiling code for photon
Including:
blink.ino
Compile succeeded.
Memory use:
Flash …
```
> feat: [sc-120185] Support assets in particle cloud flash

- src/app/cli.js
- src/app/ui.js
- src/cmd/cloud.js
- src/cmd/flash.js
- src/cmd/flash.test.js
- src/cmd/usb-util.js
- src/lib/device-os-version-util.js
- src/lib/device-specs.js
- src/lib/file-types.js
- src/lib/known-apps.js
- src/lib/known-apps.test.js
- src/lib/ui/index.js
- src/lib/ui/index.test.js
Parse command-line argument for local flash
> Feature/sc 121027/get files to flash

- npm-shrinkwrap.json
- package.json
- src/cmd/bundle.test.js
- src/cmd/flash.js
- src/cmd/flash.test.js
This is a first implementation of Flash that uses naive flash steps, assuming the binaries are already in the right which isn't always the case. Hugo, when you have your method to generate flash steps, we can delete my temporary version.
> Feature/sc 121029/flash files locally

- test/README.md
After trying the E2E tests, I came with some small updates that could proof helpful for whoever tries them in the future
> Add known issues to e2e readme

- npm-shrinkwrap.json
- package.json
Use the latest version of `particle-api-js`
1. Pull the branch
2. Install new dependences `npm run reinstall`
3. Run unit tests `npm run test:unit`
4. Follow instructions in ./test/README.md to run e2e tests
5. Run multiple commands locally to check they pass `npm run -- CMD ...` , such as listing devices, compiling, uploading a product firmware
All tests should pass (some e2e tests are unstable and depend on specific env variables so they could fail due to that)
> update dependency particle-api-js@^10.0.0

- npm-shrinkwrap.json
- package.json
- test/e2e/project.e2e.js
The new Particle Project template!
1. Check out this branch locally and install dependencies using `npm install`
2. Run `npm start -- project create` and verify that the project structure is as expected
See example here : https://github.com/particle-iot/particle-commands/tree/master/test/fixtures/projects/myProject
```
├─ myproject
│
├─ src
│  └─ myproject.cpp
│
├─ README.md
│
├─ .gitignore
│
├─ particle.properties
│
├─ .github
├─ workflows
└─ main.yaml
```
- https://www.notion.so/particle/Proposal-Brief-for-Updating-the-Default-Particle-Project-Template-adc07efd15de4d2a8d1289e3aa69c899
- https://github.com/particle-iot/particle-commands/pull/22
- https://github.com/particle-iot/particle-commands/pull/20
> New Particle Project Template

- test/e2e/library.e2e.js
- test/e2e/project.e2e.js
> skip e2e tests

- src/cmd/logic-function.js
- src/cmd/logic-function.test.js
- src/lib/logic-function.js
- src/lib/logic-function.test.js
- src/lib/template-processor.js
- src/lib/template-processor.test.js
This PR contains the changes regarding the `lf` refactor for `create` command
Also this PR fix the structure for `logic.json` file to meet the SDD requirements
1. Pull down the branch: `git pull && git checkout feature/sc-124023/create-refactor`
2. Install dependencies: `npm i`
3. Run tests: `npm run test:ci`
4. Attempt to create a new logic function
* without params: `npm start -- lf create /my/lf/path`
* With name param: `npm start -- lf create --name "my logic function name" /my/lf/path`
* with org param: `npm start -- lf create --org /my/lf/path`
5. Attempt to get an existent logic function
***outcome***
* Test should pass
* create without params will ask you to write `name` and `description`
* create with params will skip the prompt for a `name`
* create for an org will still work
* …
> Feature/sc 124023/create refactor

- .github/workflows/reusable-publish-npm.yml
- scripts/generate-manifest.js
* Use the right token to publish to npm
* Fix the url for downloading old versions of particle cli win installer
> Bug/sc 128408/manifest json for installers have bad urls

- src/cmd/flash.js
- src/cmd/update.js
- src/lib/flash-helper.js
- src/lib/flash-helper.test.js
> Flash protected bootloader on Protected Devices

- src/cli/device-protection.js
- src/cmd/device-protection.js
- src/cmd/device-util.js
- src/cmd/flash.js
- src/cmd/keys.js
- src/cmd/keys.test.js
- src/cmd/update.js
- src/cmd/usb-util.js
- src/lib/device-protection-helper.js
- src/lib/flash-helper.js
- src/lib/flash-helper.test.js
- test/e2e/keys.e2e.js
Support Protected Devices while running `particle keys xxx` commands
Run `particle keys xxx` commands on
- Open Devices any version
- Protected Devices (latest develop-6.x branch because develop-6x has the latest fixes that need to work with Protected Devices in dfu mode)
> Automate Protected Devices to run `particle keys` commands 

- npm-shrinkwrap.json
- package.json
As title says.
Run `npm test`
https://github.com/particle-iot-inc/device-constants/pull/40
> Update device constants for gen4

- src/cli/logic-function.js
Story details: https://app.shortcut.com/particle/story/128278
> feat: [sc-128278] Make --org flag for logic function commands in CLI visible

- src/cli/tachyon.js
- src/cmd/setup-tachyon.js
Read time from computer using `Intl.DateTimeFormat().resolvedOptions().timeZone`, or taking from the `--timezone` option, or taking from the JSON config. Pass it to the config blob to Tachyon.
Also tweak a few things in the setup command:
- 3 GB download.
- Put Create new product at the bottom of the list.
- Don't allow blank system password.
> Pass initial timezone to Tachyon during setup

- src/cmd/setup-tachyon.js
Improvements for Tachyon setup:
- Ensure API works after login
- Ensure product name is not blank.
- Ensure SSH key is a public key.
- Don't reference organizations at the top level since not everyone is in an org.
> Tachyon setup fix

- src/cli/tachyon.js
- src/cmd/download-tachyon-package.js
- src/cmd/setup-tachyon.js
- src/lib/platform.js
Add `--variant` flag in setup command by default `headless`
* Attempt to run tachyon setup with variant flag: `npm start -- tachyon setup --variant headless`
* Attempt to run tachyon setup with a nonexistent variant: `npm start --tachyon setup --variant foo`
* Attempt to run tachyon setup without variant flag: `npm start --tachyon setup`
**outcome**
1. With an existent variant, the download step will download the correct package
2. With a nonexistent variant, the download step will fail with: `No builds available for the selected region or variant`
3. Without  a variant, the download step will download the package with the headless variant
Story details: https://app.shortcut.com/particle/story/133909/
> Feature/sc 133909/add variant to tachyon setup

- src/cmd/api.js
- src/cmd/setup-tachyon.js
Fix setup issues for getting product and variant 
story details: https://app.shortcut.com/particle/story/133952/tachyon-setup-issues
> Bug/sc 133952/tachyon setup issues

- src/cmd/setup-tachyon.js
- src/lib/download-manager.js
Add board pick for `rb3` boards
* Attempt to setup with board `rb3`: `npm start -- tachyon setup --board rb3g2`
**outcome**
* variant list should returns `❯ preinstalled server`
* rb3g2 package should be downloaded and ready to install
Story details: https://app.shortcut.com/particle/story/133963/handle-use-new-board-rb3gen2
> allow rb3 board types

- src/cmd/app.js
Ensure app run can access the X server on Tachyon
> app run: provide access to the X server to Docker

- src/cmd/app.js
Use the new patch format when modifying the device's system doc.
> Use the new document patch format

- src/cli/tachyon.js
- src/cmd/backup-restore-tachyon.js
Story details: https://app.shortcut.com/particle/story/134349
Update to #816 to back up nvdata1, nvdata2, fsc, fsg, modemst1, modemst2.
> feat: [sc-134349] Back up additional partitions for Tachyon

- src/cmd/backup-restore-tachyon.js
- src/cmd/flash.js
- src/lib/tachyon-utils.js
Add meaningful logs to tachyon `flash` `backup` `restore` commands
###Outputs:
**Flash**
```
Tachyon Logs:
==================
Command: Tachyon Flash
Using Device ID: 422a060000000000xxxxxxxx
Start time: 2025-04-16T22:31:51.962Z
==================
Manifest Info:
==================
Release name: tachyon-ubuntu-20.04-NA-desktop-1.0.89
Version: 1.0.89
Region: NA
Variant: desktop
Platform: qcm6490
Board: formfactor
OS: linux
Distribution: ubuntu
Distribution version: 20.04
Distribution variant: ubuntu
Build date: 2025-04-07T22:24:07.917024
Command: .....
.....
.....
......
OS Download complete.
==================
Process Done
End Time: 2025-04-16T22:37:24.670Z
Duration: 332.71s
==================
Tachyon Log Ended
==================
```
**Backup**
```
Tachyon Logs:
==================
Command: …
```
> Feature/sc 134338/enhance particle flash tachyon logs for

- src/cmd/usb-util.js
Filter out tachyon devices when flashing firmwares
* Connect a tachyon and another device (the one you want to flash) 
* Run usb list: `npm start -- usb list`
* Run flash --local: `npm start -- flash --local /path/to/flash`
* Usb list shows both: tachyon and the other device
* On flashing CLI will ask you to pick the device you want to flash
* Usb list still showing both devices.
* On flashing CLI will recognize just one device (not the tachyon) and will start the flashing process right away
Story details: https://app.shortcut.com/particle/story/134448/remove-linux-devices-when-flashing-non-linux-devices
> filter out linux devices when opening a device

- src/cmd/setup-tachyon.js
Import device into a product before generating registration_code on tachyon setup.
This change will prevent device creation since it will fail in case we can't import the device into a product.
* Attempt to setup your tachyon
Story details: https://app.shortcut.com/particle/story/134502/change-cli-tachyon-setup-for-esim-implementation
> import device to a product before generating registration code

- npm-shrinkwrap.json
- package.json
- src/cmd/setup-tachyon.js
Add a USB version line to the device info with a yellow warning (use a USB 3.0 port and USB-C cable for faster flashing) when using a slow cable.
TODO before merging:
> Setup slow USB

- npm-shrinkwrap.json
- src/cmd/setup-tachyon.js
- src/lib/download-manager.js
- src/lib/wifi-scanner.js
Change padding and messages from tachyon setup
> apply patch with padding

- npm-shrinkwrap.json
- package.json
> Update dependencies using spark

- src/cmd/setup-tachyon.js
Add initialTime as part of tachyon setup config blob.
> inject initial time on tachyon setup config blob

- src/cmd/setup-tachyon.js
Remove `board` from config in order to prevent board type overwriting.
`--board` flag still present in case is necessary.
1. Attempt to setup a device with a config file: `npm start tachyon setup -- --load_config ${config-file}
The config file should have `board` property (e.g.):
```
{
"region": "NA",
"version": "latest",
"variant": "desktop",
"board": "formfactor_dvt",
"skipCli": false,
"systemPassword": "${encrypted_password}",
"productId": 9999,
"timezone": "America/Merida",
"wifi": {
"ssid": "{SSID}",
"password": "{PASSWORD}"
},
"country": "US"
}
```
**outcome**
Even with `board` in config, the device should use the right `board` according device information.
story details: https://app.shortcut.com/particle/story/134831/remove-board-from-config-tachyon-setup
> remove board in config file to prevent board overwriting

- src/cli/tachyon.js
- src/cmd/download-tachyon-package.js
- src/cmd/setup-tachyon.js
Fix default channel for setup tachyon
> fix the default channel for setup config

- src/cmd/setup-tachyon.js
Refinements to the Tachyon setup text.
> Small tweaks to the Tachyon setup text

- src/cmd/app.js
Story details: https://app.shortcut.com/particle/story/134988
* Add check for migrated applications before push/remove/list commands so the user knows they need to update their particle-linux version
* Update push to use upsert action
* Update remove to use remove action
* Update list to support rendering array style apps/containers
> feat: [sc-134988] Support app push/remove/list with applications as arrays

- src/cli/app.js
- src/lib/maintenance.js
Show under maintenance message for all `app` commands
1. Pull down the branch: `git pull && git checkout chore/sc-135120/put-under-maintenance-app-commands`
2. Attempt to use all `app` commands: 
* `npm start -- app run`
* `npm start -- app list`
* `npm start -- app remove`
* `npm start -- app push`
**outcome**
All commands should print out a message indicating the command is under maintenance
> put under maintenance app commands

- npm-shrinkwrap.json
- package.json
Update device-constants to 4.0.2 with a fix to deviceId generation when it comes from `machineId`
* Attempt to identify your tachyon: `npm start -- tachyon identify`
**outcome** 
* The deviceId should be returned in lower case
> update device-constants to 4.0.2

- src/cmd/setup-tachyon.js
Improve the instructions for Tachyon Wi-Fi setup.
> Put the info about Wi-Fi only above the Wi-Fi question

- .github/workflows/reusable-build.yml
- npm-shrinkwrap.json
- package.json
- src/cmd/backup-restore-tachyon.js
- src/lib/utilities.js
* Compress backup files into a zip on backup command.
* Pull down the branch: `git pull && git checkout feature/sc-135565/update-backup-command-to-output-a-zip-file`
* Backup a tachyon device: `npm start -- tachyon backup`
**outcome**
Console Output
```
Backing up NV data from device 422a06000000000048425401...
Logs will be saved to /Users/hugo/.particle/logs/tachyon_422a06000000000048425401_backup_1758646973643.log
Created File: manufacturing_backup_422a06000000000048425401.zip
SHA256: daabef8577b750f81e299cab76f1d14d9504b5188b3ed5b58220c333fd61ceda
Backing up NV data from device 422a06000000000048425401 complete!
```
Log Output:
```
Tachyon Logs:
==================
Command: Tachyon backup
Using Device ID: 422a06000000000048425401
Start time: 2025-09-23T17:02:53.643Z
================== …
```
> Feature/sc 135565/update backup command to output a zip file

- src/cli/tachyon.js
- src/cmd/tachyon-factory-restore.js
Update `restore-factory` to get backups from cloud as `restore` command does.
* Attempt to restore a device with a `manufacturing_backup_${deviceId}.zip` file: `npm start -- tachyon restore`
* Attempt to restore a device with an specific zip file: `npm start -- tachyon restore --filePath /my/file/path/file.zip`
* Attempt to restore a device without a present backup file: `npm start -- tachyon restore` (no zip file in the path)
* Attempt to restore a device but forcing download the backup from cloud: `npm start -- tachyon restore --from-local`
**_Notes_**
Since `api-service` is not ready yet the `/v1/devices/${deviceId}/backup_files` to return a zip file with the backup.
Story details: https://app.shortcut.com/particle/story/135567/update-factory-restore
> add force-cloud for backup download on restore-factory
