particle-iot/particle-cli

commands/SetupCommand/index.js
The setup command wasn't working on Linux, fixing the case here seemed to help.
=> Typo in setup command

commands/CloudCommands.js, lib/ApiClient.js
- core —> device
- console output is now removed from `ApiClient.js`
Old output:
```sh
Failed to rename device, server said  [ 'Name already in use' ]
Potentially unhandled rejection [1] {"ok":false,"errors":["Name already
in use"]} (WARNING: non-Error used)
```
Now:
```sh
Failed to rename photon-1, server said [ 'Name already in use' ]
```
=> resolve error if renaming fails

README.md, commands/KeyCommands.js
- core —> device
- require user to only specify a filename as mentioned in `console.log()`
From: https://github.com/spark/spark-cli/pull/176
=> add `.der` to saved keys file

commands/AccessTokenCommands.js
- This should reduce @_@ by showing which account the user is currently on.
- Mention `enter password` instead of `re-enter` since they are not re-entering
Fixes: https://github.com/spark/spark-cli/pull/177
=> Print-out account username

commands/WebhookCommands.js, lib/ApiClient.js
- update `.json` template
- coreID —> deviceid
- check that `.json` file is found
- check that `.json` file can be parsed or fail
- `particle webhook GET` works now
- `particle webhook POST` works now
- `particle webhook create xxx.json` has also been tested
- print out `hookID` upon hook creation
=> Webhook fixes

commands/CloudCommands.js, lib/ApiClient.js
- take in extra param for `deviceType`
- Fixes: https://github.com/spark/particle-cli/issues/15
- Fixes: https://github.com/spark/particle-cli/issues/16
**Docs:**
To compile code using the Cloud build farm, you need to specify the target device. 
- eg. Target a Photon
- `particle compile photon xxxx`
- `particle compile p xxxx` <---- short-form to reduce typing per compile
- eg. Target a Core
- `particle compile core xxxx`
- `particle compile c xxxx` <---- short-form to reduce typing per compile
- eg. No device specified 
- `particle compile`
Error:  `Please specify the target device type. eg. particle compile photon xxx`
The current PR insists on a deviceType to be passed but we can also make it optional and default to `core` if that's better.
Signed-off-by: Kenneth Lim …
=> Compile for specific device

commands/SerialCommand.js
- tested on Windows with Photon and Core
- to be tested for Mac
- New logic to first detect `Spark`, `Photon`, `Particle` in `manufacturer` field
- Not the best for the long run and the better solution is to make the
Windows Driver say `Spark Devices` for manufacturer field
- checks `pnpId` for Windows and `vendorId` + `productId` for mac/linux
Similar fix to: https://github.com/spark/particle-cli/pull/11
=> Improve Serial device detection

commands/CloudCommands.js, commands/FlashCommand.js, lib/ApiClient.js
Fix #66 by properly formatting the output of the `particle flash` command when the compilation fails.
Note: I signed the CLA.
=> Properly format the compilation output of the flash command

lib/dfu.js
Use sudo when `useSudoForDfu` option is `true` for every dfu command.
Should fix issue #51
=> Fix for Incomplete use of 'sudo' when running 'dfu-util'

commands/SerialCommand.js
This will check that the non-empty SSID is entered before prompting further.
Fixes: https://github.com/spark/particle-cli/issues/62
Error message is: `>> please enter a valid SSID`
=> validate SSID prompt

commands/CloudCommands.js
This will reduce friction from the updated compile command. Fixes: https://github.com/spark/particle-cli/issues/58
=> add compile syntax examples upon invalid input

README.md
Looks like "core" needs to be lowercase in the path.
=> Fix path for documentation URLs

lib/dfu.js
Based on https://github.com/spark/particle-cli/commit/31299a53098c6336be1e35e1db77367e4b1f8361,
the change from `for loop()` to `forEach` does not bail out on the `return` and ends up executing code below.
Without this fix, there's always a `Apparently I didn't find a DFU device? util said  dfu-util 0.8` statement
=> fixed resolve error

README.md
It looks like the DFU Utils are no longer hosted at GNUMonks? I've replaced those links with the one from Source Forge.
=> Updated URL for DFU Utils

commands/WebhookCommands.js
Both forms are shown in the documentation: [shows eventName](https://docs.particle.io/guide/tools-and-features/webhooks/#what-39-s-in-a-request-) and [shows event](https://docs.particle.io/guide/tools-and-features/webhooks/#templates)
[This trips users up](http://community.particle.io/t/cannot-create-very-simple-webhook-please-specify-event-name-error/14196) so just accept either :)
=> Accept either event or eventName in the webhook JSON

commands/WebhookCommands.js, lib/ApiClient.js
uses a bearer token and a JSON request so we don't form-encode /  'stringify' native types in the request body.  Fixes https://community.particle.io/t/webhook-adding-double-quotes-to-boolean-value/15199/2
=> fixes native types being form-encoded which causes them to lose type info

lib/50-particle.rules, lib/dfu.js
On Linux only root can access USB devices through dfu. Right now doing `particle flash --usb` will say "no dfu device found" without suggesting how to fix the issue.
It's possible to use sudo to work around this, but a better solution is to install UDEV rules to allow any user to access a particular device.
This PR prompts the user to install UDEV rules when the dfu-util failure indicates missing permissions.
The UDEV rules was checked for the Photon on Ubuntu 15.10. I included rules for the Core, P1 and Electron, but I can't try those.
Somebody working on the CLI should review the code and check if I put the code in the right place as I'm not familiar with the structure of the application.
This fixes #74.
=> Prompt to install UDEV rules for dfu

README.md, mappings.json
- mention about public/private flags
- updated the syntax example
=> Update publish docs

commands/SerialCommand.js, lib/deviceSpecs/specifications.js
On (at least my) Linux Ubuntu 15.10, the reported vendor ID and product ID are the bus IDs instead of the device IDs. As a backup to the VID and PID identification, do a string matching on the `serialNumber` reported by the `serialport` module.
The expected strings for the Core, Photon and Electron are:
```
serialNumber: 'Spark_Devices_Spark_Core_with_WiFi_6D7238764957',
serialNumber: 'Particle_Photon_with_WiFi_00000000050C',
serialNumber: 'Particle_Electron_00000000050C',
```
Fixes #190
=> Use serialNumber to identify serial devices on Linux

lib/deviceSpecs/specifications.js
- DFU works (tested sys1, sys2, user, factory)
- Serial works (wifi, inspect, identify)
- Not sure about the public/private keys address location though
- serialNumber: 'RedBear_Duo' is not verfied as this shows up in linux but should be correct based on https://github.com/redbear/firmware/blob/duo/bootloader/src/stm32f2xx/usbd_desc.c
- fixes https://github.com/spark/particle-cli/issues/173
=> device: add duo support

commands/UdpCommands.js
I chatted about this with @dmiddlecamp this morning (morning of 2016-02-24).  It's fleshing out a "stub" at https://github.com/spark/particle-cli/blob/master/commands/UdpCommands.js#L49 to give users an easy way to broadcast UDP messages from their devices and monitor them without resorting to complicated tools like tcpdump or Wireshark.
=> Added UDP listen command

commands/WirelessCommand/WiFiManager.js, commands/WirelessCommand/connect/linux.js, package.json
Use the NetworkManager CLI (the standard Linux network configuration tool suite on Fedora, Debian, Ubuntu, Gentoo, CentOS or openSUSE) to switch to the Photon AP and reconnect to the wifi
Needs spark/node-wifiscanner#1 to be merged and a new version of node-wifiscanner2 to be added to the Particle CLI package.json in order for the WiFi scanning to work.
Tested on Ubuntu 15.10
=> Connect to wifi network on Linux during setup

.travis.yml, package.json
On Node.js v6, serialport was logging a huge warning for every particle-cli command, even ones that were unrelated to the serial port. See https://github.com/voodootikigod/node-serialport/issues/780 for details.
This change just bumps the serialport dependency to the latest release, which resolves the issue.
All the tests still pass and I did some basic manual testing and didn't see any issues.
=> bump serialport dependency version for Node.js v6

settings.js
Allow the CLI installer to start the CLI without the update check.
=> Disable update check through an environment variable

oldlib/prompts.js, package.json, src/cli/library_add.js, src/cli/library_init.js, src/cli/library_install.js, src/cli/library_migrate.js, src/cli/library_publish.js, src/cli/library_search.js, src/cli/library_upload.js, src/cli/project_init.js
Prompts the user for a name and directory as detailed in the product spec.
Also makes the library command descriptions consistent.
renames `init` to `create`.
=> project init dialog

commands/WebhookCommands.js
- allows mass deletion of all webhook
- logic might need to be improved. current might not be async?
- test to be implemented for completeness
- docs PR will be required as well
Signed-off-by: Kenneth Lim kennethlimcp@gmail.com
=> webhook: added delete all command

commands/SerialCommand.js
Hi,
Previously submitted a PR (https://github.com/spark/particle-cli/pull/225) (and sent a release) that appeared to be accepted but wasn't merged. I've gone through and re-added the code and made the necessary adjustments to deal with things like args now being an array. It'd be awesome if this time it was merged to save folk time when setting up a _lot_ of Particles.
**Background:**
As the serial command currently expects any 'extra' arguments to be the serial com device, you need to append the .json argument to the end, ie: 
particle serial wifi /dev/cu.usbmodem1411 variables.json
variables.json looking like:
{
"network":"mynetworkssid",
"security":"WPA_AES",
"password":"mySecret!"
}
=> Updated again to accept a variables.json argument

accept/features/cloud_flash.feature
Related to: https://github.com/spark/particle-cli/issues/331
This PR probably did not handle the flashing of knownApp: https://github.com/spark/particle-cli/commit/eadd6790e83c19f180557a0ac8e4548ebd0d1eb3
Output from `fileMapping` using a knownApp: 
```
{ list: [ '/Users/kennethlimcp/Desktop/particle/particle-cli/binaries/photon_tinker.bin' ] }
```
Output from `fileMapping` for source files:
```
{ basePath: '/Users/kennethlimcp/Desktop/particle/particle-cli',
map: { 'test.ino': '../../test/test.ino' } }
```
=> add: test case for flashing knownApp

settings.js, src/app/app.js
Loads native modules as part of startup to capture any loading issues. If they fail to load, the user is prompted to reinstall the CLI. fixes #322
=> native module preemptive loading

commands/CloudCommands.js, oldlib/ApiClient.js
addresses https://github.com/spark/particle-cli/issues/287
```
$particle flash electron2 tinker --yes
! Skipping Bandwidth Prompt !
attempting to flash firmware to your device electron2
...
```
This also fixes an error due to a missing `.map` property on `fileMapping` when flashing a known app. (seems there are multiple paths for known apps - we fixed one just a few weeks ago, this PR fixes the other one.)
=> adds a `—yes` parameter to skip the bandwidth prompt

commands/KeyCommands.js, commands/SerialCommand.js
submitted to fix compatibility with older node versions, specifically fixes the following:
```
Error loading command .../particle-cli/commands/KeyCommands.js SyntaxError: Unexpected token (
Error loading command .../particle-cli/commands/SerialCommand.js SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
```
=> fixes compatibility with older node versions

commands/SerialCommand.js
First argument was incorrectly being bound to `this`, when creating a partially applied `parseSecurityType` function.
Closes #375
=> Fixes `wifi setup` (issue #375)

README.md
In addition to installing and uninstalling, I'd thought it made sense to also show users how to **_update_** particle-cli.  There is a section on Particle Docs on how to do this, but I thought it might be convenient to see it on the Github repo which is where I was looking for it and couldn't find it.
=> update particle-cli on README.md

src/cli/serial.js, src/cmd/serial.js, src/cmd/setup.js
=> Set up wifi using credentials from a JSON file

src/cmd/cloud.js
Since the Electron now has 3 MB of data per month, it doesn't make sense anymore to prompt people to accept flashing applications that are typically 0.01 MB in size.
https://app.clubhouse.io/particle/story/15292/remove-data-usage-warnings-for-electrons
=> Remove Electron flash data warning

src/cmd/cloud.js, src/cmd/function.js, src/cmd/variable.js, test/cmd/function.spec.js
* Fix server error when Particle.function returns 0
* Only print timestamp when using the --time flag
=> Fix issue with function and variable commands

src/lib/deviceSpecs/specifications.js, src/lib/ymodem.js
Support Xenon YModem firmware updating, set initial response timeout to 10 seconds because it takes about 6 seconds to send initial response on Xenon.
=> Add Xenon support, set initial response timeout to 10 seconds

src/cmd/serial.js
This PR introduces the following changes:
- Show NCP firmware modules in the output of the `serial inspect` command.
- Increase the timeout of the `s` and `i` serial commands sent to the device.
Example output of the `serial inspect` command with an Argon device:
```
Platform: 12 
Modules
Bootloader module #0 - version 300, main location, 49152 bytes max size
Integrity: PASS
Address Range: PASS
Platform: PASS
Dependencies: PASS
System module #1 - version 1002, main location, 671744 bytes max size
Integrity: PASS
Address Range: PASS
Platform: PASS
Dependencies: PASS
Bootloader module #0 - version 201
User module #1 - version 6, main location, 131072 bytes max size
UUID: 8C3E879F1032133D7F456603A8A52DDFBA1102CF472FFC376CED0D69075FB7C3
Integrity: PASS
Address Range: PASS
Platform: PASS …
```
=> Show NCP firmware modules in the output of `serial inspect`

npm-shrinkwrap.json, package.json, src/cmd/mesh.js
This PR introduces the following changes:
- When adding an unclaimed device to a network, make sure the device is removed from its current network first (see [ch30101](https://app.clubhouse.io/particle/story/30101/half-initialized-mesh-networks-make-mesh-device-unable-to-be-provisioned) for the details).
- Filter out duplicate entries from the list of discovered networks (see [this](https://s.slack.com/archives/CG6D5KB43/p1555091439015800?thread_ts=1554999936.004900&cid=CG6D5KB43) discussion and the related [fixes](https://github.com/particle-iot/device-os/pull/1760) in the Device OS).
- Remove the workaround for the API service issue that was fixed in https://github.com/particle-iot/api-service/pull/601.
=> Mesh command fixes

settings.js
When updating system firmware with `particle update` with CLI 1.43.0 on Photon/P1, the device locks up at the last step where DCT is written to.
**Short term solution:** Need to flash Bootloader and OTA Flag before system parts for Photon/P1 because as soon as the system parts are flashed they will change the location of DFU read/write functions which live in system firmware.
**Long term solution:** Add a dirty flag in Device OS that would cause the bootloader to reload DCT functions from system parts if their flash area has been modified.  Will be added to a future Device OS release.
Fixes #498 
https://community.particle.io/t/device-os-1-2-1-and-particle-cli-1-43-fail-in-particle-update/51140
=> Fixes issue #498 where `particle update` fails on Photon/P1

npm-shrinkwrap.json, package.json, src/cmd/binary.js, src/cmd/flash.js, src/cmd/serial.js, src/lib/deviceSpecs/specifications.js
This PR:
1. adds support for 'radio stack' modules
2. adds support for `DROP_MODULE_INFO` module flag introduced in https://github.com/particle-iot/device-os/pull/1816 when flashing over DFU
3. prints secondary module dependency information in `binary inspect`
Follow the guide in https://github.com/particle-iot/device-os/pull/1816, or use the following pre-built [Argon binaries](https://github.com/particle-iot/particle-cli/files/3276558/argon-binaries.zip) and flash `system-part1` and `bootloader` to the device.
1. `particle binary inspect argon-softdevice-6.1.1.bin` should work correctly:
```console
CRC is ok (78715fba)
Compiled for argon
This is a radio stack module number 0 at version 182
It depends on a system module number 1 at version 1300
It also depends on a bootloader number 0 at …
```
=> adds support for radio stack modules

src/cmd/flash.js
This PR resolves a regression introduced in #493 when flashing known apps (e.g. tinker).
Closes #501
=> flash: fixes a regression in flash command for known apps

settings.js, src/cmd/serial.js
Background:
We're investigating a CLI crash on a long-running `particle serial monitor --follow` invocation that runs out of memory after ~4 hours or so.
Theory:
The follow command has a 5ms timeout before it checks for serial ports again, heavily taxing the operating system.  By making this a setting, we can more easily test a longer timeout without changing behavior for everyone.  We suspect a 50, or 100ms timeout will be easier on the host OS, and provide equivalent behavior.
Thanks!
=> moves hardcoded 5ms timeout to settings file

src/cli/cloud.js, src/cmd/cloud.js, src/lib/utilities.js, test/__fixtures__/projects/symlink/main-project/app.ino, test/__fixtures__/projects/symlink/main-project/project.properties, test/__fixtures__/projects/symlink/main-project/shared, test/__fixtures__/projects/symlink/shared-project/sub_dir/helper.cpp, test/__fixtures__/projects/symlink/shared-project/sub_dir/helper.h, test/e2e/compile.e2e.js
This PR sets `follow` to `true` when resolving files for compilation.
Docs of `glob` module: https://www.npmjs.com/package/glob
Run `particle compile photon test/__fixtures__/projects/symlink/main-project`. It should include thie following files:
```
Including:
test/__fixtures__/projects/symlink/main-project/shared/sub_dir/helper.h
test/__fixtures__/projects/symlink/main-project/app.ino
test/__fixtures__/projects/symlink/main-project/shared/sub_dir/helper.cpp
test/__fixtures__/projects/symlink/main-project/project.properties
```
Without this PR, the output is the following:
```
Including:
test/__fixtures__/projects/symlink/main-project/app.ino
test/__fixtures__/projects/symlink/main-project/project.properties
```
...which results in a compilation error due to missing header …
=> Follow Symlinks while Globbing File List

src/app/ui.js
Commands like `particle mesh` and `particle usb` often include a terminal spinner, that spinner was not moving. This patch fixes that by changing the call to `spinner.stop` to be asynchronous. I opted to not include a test as this is a minor UI feature
1. Hook up a device
2. `particle usb reset`
3. observe spinner being awesome
=> Fix UI spinner stopping immediately

src/cmd/serial.js, src/cmd/serial.test.js, test/__mocks__/serial.mock.js
Previously when `particle serial wifi` was used and the device wasn't put in listening mode ahead of time, the command would appear to hang, forcing the user to ctrl+c or otherwise kill the process.
This patch adds the missing timeout, and adds the first tests around the `SerialCommand`'s wifi handling. 
`src/cmd/serial.test.js` contains automated testing for this.
1. Have no devices plugged into your machine.
2. Plug in device with wifi such as a Photon and wait for it to boot to breathing cyan
3. Run `particle serial wifi` and answer no to the scan question.
4. Without patch: this would wait forever, with patch after 5s you should get a message suggesting you try `particle usb start-listening`.
This is related to, but does not solve this clubhouse ticket: …
=> add timeout to `particle serial wifi` command to catch if device isn't listening

src/cli/usb.js, test/e2e/help.e2e.js
This is a quality of life improvement. The `particle usb start-listening` command is long. I'd prefer typing `particle usb listen`.
I considered adding single letter aliases for all mode change commands like `particle usb l` (listen), `particle usb x` (exit listening), `particle usb s` (safe mode), `particle usb d` (dfu), `particle usb r` (reset) but that seemed excessive.
- Connect a device
- Run `particle usb l` to enter listening mode
This alias should be documented here: https://github.com/particle-iot/docs/blob/master/src/content/reference/developer-tools/cli.md#particle-usb
=> Add aliases for usb mode change commands

src/cli/usb.js, src/cmd/usb.js, test/e2e/help.e2e.js, test/e2e/usb.e2e.js
This PR implements a new command that sets/clears the setup done flag on Gen 3 devices:
```
particle usb setup-done my_device
particle usb setup-done --reset my_device
```
```
npm run test:e2e
```
- [ch46416]
=> Add a command to set the setup done flag

src/cli/cloud.js, src/lib/api-client.js, test/e2e/cloud.e2e.js
`particle cloud claim` fails when a mixed-case device id is provided.
**Repro Steps**
1. run `particle cloud claim <device id w/ all lowercase characters>`
2. run `particle cloud claim <device id w/ uppercase characters>`
**Expected**
both commands should succeed
**Actual**
1st command succeeds, 2nd command fails w/ "Failed to claim device: device not found"
=> always send lowercase device id when claiming a device

assets/50-particle.rules
Current udev rules need to be modified for each platform. They are missing B5 SoM support right now. Until we change the pattern, we can assume that any device that matches our USB vendor ID and has a product ID starting with c0 or d0 will have the same behavior.
Validated this file on my Ubuntu machine with a B5 SoM.
=> Simplify udev rules

src/cli/usb.js, src/cli/usb.test.js, src/cmd/cloud.js, src/cmd/usb.js, src/lib/utilities.js, src/lib/utilities.test.js, test/e2e/cloud.e2e.js, test/e2e/usb.e2e.js
Story details: https://app.clubhouse.io/particle/story/51710
=> Allow list filters to work with usb list command

src/cli/cloud.js, src/cli/cloud.test.js, test/e2e/cloud.e2e.js
The `particle nyan --help` had different device name in the command and the description of the command's effect. Reconciled that.
Check the results by `particle nyan --help`, and the existing automated tests were also update.
N/A
=> nyan: fix disconnect between command and description in help

src/cli/config.js
Adds minimal documentation for newly added `proxyUrl` parameter of `config` command
run: `particle config --help`
see "Examples" section
Continues https://github.com/particle-iot/particle-cli/issues/108 
Originally fixed in https://github.com/particle-iot/particle-cli/commit/1345fbb769f2391165b925a3a137737e7f0a24aa
=> Add proxyUrl example to config help

npm-shrinkwrap.json, package.json, src/cmd/flash.js
In preparation for 3.1.0-rc.1 Device OS release with support for [256KB (vs 128KB prior) application binaries](https://docs.google.com/document/d/1DvOFlKDMDqB1JotDDHTFnWLNPyqYZ9ZADfSXr4W8P9U/edit#heading=h.vc7udwm4tepa), CLI needs to be updated to take destination address when performing DFU flashing from the binary module prefix, instead of using a hardcoded location.
This PR also bumps `binary-version-reader` dependency to the version with particle-iot/binary-version-reader#41, which improves how module prefixes are parsed.
I have not updated `src/lib/deviceSpecs/specifications.js` with the new location of the user application binary for Gen 3 platforms. This new location is only true for devices running >= 3.1.0, but it should not matter much anyway given that we are taking the …
=> [Gen 3] 256KB application binary support when flashing over DFU

.circleci/config.yml
Story details: https://app.shortcut.com/particle/story/104725
When we attempt to run the npm-publish job, CircleCI throws a "No
Workflow" error. This is due to the version declaration we included in
the workflow. We don't need it as we have already declared the version
on line 1 and it is the wrong version. Likely a copy paste error. For more context, see the CircleCI post titled
[No workflow when create release through github](https://discuss.circleci.com/t/no-workflow-when-create-release-through-github/388022).
My hope is that once we get this PR merged to main, we can republish the tag and it will work as expected.
=> fix: [sc-104725] `particle-cli` package failed to publish `v3.2.0` tag via CircleCI

npm-shrinkwrap.json, package.json, src/cli/cloud.js, src/cli/cloud.test.js, src/cli/usb.js, src/cli/usb.test.js, src/cmd/cloud.js, src/lib/utilities.js, src/lib/utilities.test.js, test/e2e/compile.e2e.js, test/e2e/list.e2e.js
Add aliases to the platform names for particle compile command
For platforms with aliases, for example, for P2
Verify that compiling with platform `p2` and `photon2` both work
```
npm start -- compile p2
npm start -- compile photon2
```
https://app.shortcut.com/particle/story/116732/support-orson-platform-in-cli-tools
=> Add aliases to platform names

npm-shrinkwrap.json, package.json, src/cmd/api.js, src/lib/device-os-version-util.js, src/lib/device-os-version-util.test.js, src/lib/ui/index.js
Adds the library that helps to download binaries using Device Os Versions API.
This new function receives: `platformId`, `version`, an `api` instance and an `ui` instance.
This is an example on how to use
```
const UI = require('../lib/ui'); // ui from src/lib/ui/index.js
const ParticleApi = require('./api'); // from src/cmd/api
const { downloadDeviceOsVersionBinaries } = require('../lib/device-os-version-util');
const settings = require('../../settings');
const auth = 'XYZ'; // your token
async function download() {
const particleApi = new ParticleApi(settings.apiUrl, { accessToken: auth });
const ui = new UI();
const binaries =  await downloadDeviceOsVersionBinaries({
platformId: 12,
api: particleApi,
ui: ui,
version: 'latest'
});
return binaries;
}
download().then(res => …
```
=> Feature/sc 120959/implement device os version api into particle

.circleci/config.yml, src/cmd/bundle.js, src/cmd/bundle.test.js
This PR adds support to extract asset modules from a bundle.
The provided bundle.zip file is extracted locally, unpacked and wrapped into asset modules by the binary version reader.
The method `extractModulesFromBundle` returns the path of the app binary and wrapped asset modules.
=> Extract modules from bundle

src/cmd/flash.js, src/cmd/flash.test.js, src/lib/dependency-walker.js, src/lib/dependency-walker.test.js
This PR wil add the ability to get a list of modules and sort it out depending on the device mode, in that way we can get a list of steps to flash a device with the specific device mode for each module.
* Attempt to flash a device by using: 
* `npm start -- flash -- local /my/dir/binary.bin`
* `npm start -- flash -- local /my/dir/binary.bin --target x.x.x`
* `npm start -- flash -- local /my/dir/binary.bin --application-only`
repeat the same but picking a dir instead a binary
=> Feature/sc 121398/sort and create recipe for flashing a list

src/cmd/flash.js
`particle flash --local <deviceIDorName> /path/to/proj --target 5.4.1` should select the specified device
Connect at least two devices to the computer and make sure that the correct device ID provided in the above command is picked up for flashing
https://github.com/particle-iot/cli/pull/193
=> Fix the device id/name option

src/cmd/flash.js
I got `Invalid version. Must be a string. Got type "object".` when the API didn't return a value for the Device OS version for an app. In that case, bypass downloading the Device OS files. This could happen for a development release or because the API call fails (likely what happened to Eric).
=> Keep flashing if Device OS version for app cannot be determined

src/cmd/flash.js, src/cmd/flash.test.js
Change based on discussion in Slack: when doing `particle flash --local` or Workbench: Flash application (local), don't update Device OS if we can't read the version. This is most common when the device is in DFU mode. This avoids needlessfly flashing Device OS over and over.
=> Flash Device OS only when version is known to be outdated

src/cmd/flash.js, src/cmd/usb-util.js
Device selector will now show more details
With user creds and api connectivity available
```
? Which device would you like to select? (Use arrow keys)
❯ seal_penguin [0a10aced202194944a02c4d4] (Photon 2 / P2, LISTENING) 
morphing_banjo [e00fce6819ef5f971ea9563a] (Argon) 
```
Without api connectivity, it does not show the name
```
? Which device would you like to select? (Use arrow keys)
❯  [0a10aced202194944a02c4d4] (Photon 2 / P2, LISTENING) 
[e00fce6819ef5f971ea9563a] (Argon) 
```
1. Checkout his branch to test
2. Connect at least two devices
3. Run `npm start -- flash --usb app.bin`
4. Ensure the output is as expected
NA
=> Improve usb device selector output

src/cmd/flash.js, src/cmd/usb-util.js, src/lib/flash-helper.js, src/lib/flash-helper.test.js, src/lib/ui/index.js
This PR will make `flash --usb` be aware of the device mode and the platform depending on the `binary` to be flashed.
1. Connect several devices to the computer
2. put all the devices in normal mode
3. Attempt to flash an specific `user-part` application and platform
4. Put different devices (with different platforms) in DFU mode including your device
5. Repeat step 3
6. Put some devices (with the same platform) in DFU mode
7. Repeat step 3
**outcome** 
* After step 2 you will see an error indicating your device needs to be in DFU
* After step 4 your device will start flashing
* After step 6 you will see a list of devices in DFU mode that has the required platform for the user application you attempt to flash
1. Connect several devices to the computer
2. put all the devices in normal mode …
=> Feature/sc 122867/make particle usb flash be aware of device

src/cmd/usb-util.js
This PR will fix the issue regarding `flash --local` is not picking the deviceId/Name from the params
1. Connect several devices into your computer
2. Attempt to do a `npm start -- flash --local ${deviceName/id} binary.bin`
**outcome** 
The flash process will start with the selected device (into params)
Story details: https://app.shortcut.com/particle/story/122967/issue-particle-flash-local-is-not-getting-deviceid-name-from-params
=> add a missing return for single devices

src/lib/dependency-walker.js, src/lib/flash-helper.js
Story details: https://app.shortcut.com/particle/story/123209
Fixes the inability to flash monolithic debug firmware for Photon and Electron with `particle flash --local`.
=> fix: [sc-123209] Flashing Electron 2.3.1 using `flash --local` returns error

src/lib/flash-helper.js, src/lib/flash-helper.test.js
Flash mono builds over `flash --usb` command
Run `particle flash --usb /path/to/mono-firmware.bin` on mono supported builds.
=> Flash mono builds over `flash --usb` command

src/app/command-processor.js, src/cli/logic-function.js
This PR will add the ability to hide some options in help command
1. Pull down the branch: `git pull && git checkout feature/sc-123965/hide-options-in-cli`
2. Install dependencies: `npm i`
3. Run unit tests: `npm run test:unit`
4. run `--help` option for every `logic-function` command
5. Attempt to use all known options for each command.
**Outcome**
* Tests should pass
* options marked with `hidden` should not appear in help
* all options will be used
Story details: https://app.shortcut.com/particle/story/123965
=> add hide option for command options

npm-shrinkwrap.json, src/cmd/api.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js
Implements `disable` and `delete` commands for Logic Functions.
The commands are:
```
npm start -- lf delete
npm start -- lf disable
```
https://app.shortcut.com/particle/story/123399/implement-disable-command
https://app.shortcut.com/particle/story/123400/implement-delete-command
=> Feature/sc 123399/delete and disable

src/cli/logic-function.js, src/cmd/api.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js
Implements the `deploy` functionality.
Removes saving the Logic Function to a logic-function-directory and saves them directly in the CWD.
- Does NOT do `current-working-directory/LF/LF.json`
- Does `current-working-directory/LF.json`
- Create a Logic Function using `particle lf create`
- Deploy the Logic Function using `particle lf deploy`
https://app.shortcut.com/particle/story/123398/implement-deploy-command
=> CLI Logic Functions - Deploy 

src/cmd/logic-function.js, src/cmd/logic-function.test.js, src/lib/logic-function.js, src/lib/logic-function.test.js
This PR will refactor the LogicFunction list command in order to use a LogicFunction class with static methods.
* Pull down the branch: `git pull && git checkout feature/sc-124023/create-logic-function-helper-to-put-file`
* Install dependencies: `npm i`
* Run tests: `npm run test:unit`
* Attempt to list your logic functions with the different options: `npm start -- logic-function list`
* Also try it with an account without logic-functions
**outcome**
* Tests should pass
* You will see your logic functions list without any "ui" changes
* Without logic functions you'll see a message indicating that there is no logic functions deployed on your account
Story details: https://app.shortcut.com/particle/story/124023/create-logic-function-helper-to-put-file-interaction-functions-instead-of-in-cmd- …
=> Feature/sc 124023/refactor-list

src/cli/logic-function.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js, src/lib/logic-function.js, src/lib/logic-function.test.js
This PR contains all changes related with `logic-function` refactor for the `get` command.
Currently the `logic.json` creation doesn't have the right structure. That error were fixed in this PR https://github.com/particle-iot/particle-cli/pull/705
1.  Pull down the branch: `git pull && git checkout feature/sc-124023/get-refactor`
2. Install dependencies: `npm i`
3. Run tests: `npm run test:ci`
4. Attempt to:
* List logic functions: `npm start -- lf list --org ${my_org}` || `npm start -- lf list`
* Attempt to get one `lf` either for sandbox or org: `npm start -- lf get --name "my logic function" --org ${my_org} /my/path/`
* Attempt to call get `lf` without params: `npm start -- lf get`
**outcome**
* Test should pass
* list should show your `lf`
* on getting specific `lf` it will create two …
=> Feature/sc 124023/get refactor

src/cli/logic-function.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js, test/__fixtures__/logic_functions/lf3_proj/code.js, test/__fixtures__/logic_functions/lf3_proj/config.json, test/e2e/logic-function.e2e.js
`npm run test:e2e -- --grep "Logic Function Commands"`
=> Add end to end tests for CLI Logic commands

src/cli/logic-function.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js, src/lib/logic-function.js, src/lib/logic-function.test.js, test/e2e/logic-function.e2e.js
This PR will re-define the accepted params for `execute` and `deploy` and also use `class` pattern for logic function `deploy` and `execute` commands
* Pull down the branch: `git pull && git checkout feature/sc-124023/execute-refactor`
* Install dependencies: `npm i`
* Run tests: `npm run test:ci` & `npm run test:e2e -- --grep "Logic Function Commands"`
* Run over the follow suggested tests:
Having a current Logic function (you can use `npm start -- lf create` to create a fresh one) run:
* `npm start -- lf execute /my/logic/function/path`
* `npm start -- lf execute /my/logic/function/path/file.js`
* `npm start -- lf execute /my/logic/function/path/file.logic.js`
**outcome**
* In every case you will be able to execute your logic function succesfully.
Having a current Logic function (you …
=> Feature/sc 124023/execute refactor

src/cli/logic-function.js, src/cmd/logic-function.js, src/cmd/logic-function.test.js, src/lib/logic-function.js
This PR will change updateStatus command in order to use LogicFunction Class
1. Pull down the branch: `git pull && git checkout feature/sc-124023/disable-enable-refactor`
2. Install dependencies: `npm i`
3. Run tests: `npm run test:ci` && `npm run test:e2e -- --grep "Logic Function Commands"`
4. Attempt to enable/disable a logic function:
* Enable by name: `npm start -- lf enable --name "<logic function name>"
* Enable by id: `npm start -- lf enable --id "<logic function id>"
* Enable by using path: `npm start -- lf enable --name "<logic function name> /local/path/for/my/logic/function"
* Enable by wrong name:  `npm start -- lf enable --name "<wrong logic function name>"
* Disable by name: `npm start -- lf disable --name "<logic function name>"
* Disable by id: `npm start -- lf disable …
=> Feature/sc 124023/disable enable refactor

src/cmd/usb-util.js, src/cmd/usb.js
This was the issue:
```
particle.js usb list
DeviceProtectionError
at errorForRequest (/home/monkbroc/Programming/cli/node_modules/particle-usb/src/result.js:144:10)
at /home/monkbroc/Programming/cli/node_modules/particle-usb/src/device.js:917:11
at async klass.getDeviceMode (/home/monkbroc/Programming/cli/node_modules/particle-usb/src/device.js:352:13)
at async Promise.all (index 2)
at async /home/monkbroc/Programming/cli/src/lib/utilities.js:153:18
at async CLI.runCommand (/home/monkbroc/Programming/cli/src/app/cli.js:148:4)
at async CLI.run (/home/monkbroc/Programming/cli/src/app/cli.js:175:11) {
result: 'Device is protected'
}
```
Propagate device protection error gracefully from the particle-usb
Run `npm start -- usb list` on a bunch of devices with at least one protected device …
=> Add Error Handling for Device Mode Checks

npm-shrinkwrap.json, package.json, src/cli/library.js, src/cli/library_init.js, src/cli/library_init.test.js, test/e2e/library.e2e.js, test/integration/library_init.integration.js
This PR will remove Yeoman dependency and update the way we init new libraries.
1. Pull down the branch `git pull && git checkout chore/sc-125552/remove-yeoman-generator-from-particle-library`
2. Install dependencies: `npm install` 👉  Required since we removed dependencies
3. Run tests
4. Attempt to create a new library: `npm start -- library create --dir /my/path/dir`
* Use the different options from the command
**outcome**
* Tests should pass
* When creating a library you should be prompted for details like library name, version, etc.
* Your library will be created in the dir you targeted.
Story details: 
* https://app.shortcut.com/particle/story/125552
* https://app.shortcut.com/particle/story/123481
=> Chore/sc 125552/remove yeoman generator from particle library

npm-shrinkwrap.json, package.json, src/cmd/serial.js
Serialport v12 includes packages for Apple x64+arm64 so it should unblock the installer for Mac.
```
node_modules/@serialport/bindings-cpp/prebuilds/android-arm64/node.napi.armv8.node
node_modules/@serialport/bindings-cpp/prebuilds/android-arm/node.napi.armv7.node
node_modules/@serialport/bindings-cpp/prebuilds/darwin-x64+arm64/node.napi.node
node_modules/@serialport/bindings-cpp/prebuilds/linux-arm64/node.napi.armv8.node
node_modules/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv6.node
node_modules/@serialport/bindings-cpp/prebuilds/linux-arm/node.napi.armv7.node
node_modules/@serialport/bindings-cpp/prebuilds/linux-x64/node.napi.glibc.node
node_modules/@serialport/bindings-cpp/prebuilds/linux-x64/node.napi.musl.node …
```
=> Upgrade serialport to v12

.circleci/config.yml, package.json, scripts/win-sign.js
This PR will sign windows .exe output from particle-cli.
* Wait for circleci
* Download [build/particle-cli-win-x64.exe](https://output.circle-artifacts.com/output/job/2f4b219c-203e-44d9-a125-2af017e0aa7f/artifacts/0/build/particle-cli-win-x64.exe)
* Check if the signature is valid running: ` Get-AuthenticodeSignature -FilePath .\Mypath\particle-cli-win-x64.exe`
=> add sign script for win

src/lib/flash-helper.js
Story details: https://app.shortcut.com/particle/story/127227
If an asset is renamed but not otherwise modified, the CLI won't flash the newly named asset to the device, leading to the device being in safe mode.
Steps to test:
- Compile a project with one asset `test.txt`
- `particle flash --local app.zip`
- Rename the asset `test2.txt` and recompile
- `particle flash --local app.zip`
- Check that `test2.txt` is properly flashed.
I made an additional change to avoid resetting the device an additional when flashing assets in normal mode. The 2 scenarios are either that the asset is flashed, then the device reboots on its own, or the asset is skipped so an addtional reset causes the application to restart one more time than necessary.
**Hugo, can you think of a downside to this change?**
=> fix: [sc-127227] Support renamed assets

src/lib/flash-helper.js, src/lib/flash-helper.test.js
Additional fixes on top of #726
* Compare only the basename of the asset filename
* Move the command to enter listening mode to after checking if an asset should be skipped to avoid putting the device in listening mode when skipping all the assets.
=> Fix the asset check code

src/cmd/serial.js
`particle serial inspect` looks only for the asset hash. Depending on some changes, we also would like to check the asset name.
```
$ npm start -- serial inspect
> particle-cli@3.22.0 start
> node ./src/index.js serial inspect
Device: 0a10aced202194944a04af80
Platform: 35 - M SoM
Modules
Bootloader module #0 - version 2600
Size: 54.244 kB / MaxSize: 65.536 kB
Integrity: PASS
Address Range: PASS
Platform: PASS
Dependencies: PASS
Bootloader module #2 - version 7
Bootloader module #1 - version 2
Size: 4.204 kB / MaxSize: 8.192 kB
Integrity: PASS
Address Range: PASS
Platform: PASS
Dependencies: PASS
Bootloader module #2 - version 7
Size: 20.312 kB / MaxSize: 303.104 kB
Integrity: PASS
Address Range: PASS
Platform: PASS
Dependencies: PASS
System part module #1 - version 5800
Size: 1183.62 kB / …
```
=> Enhance Asset Verification by Checking Both Name and Hash

.github/workflows/dev.yml, README.md, RELEASE.md
This PR will update the README and RELEASE information to keep up to date with the new pkg strategy and the use of GitHub Actions as ci/cd process.
* Pull down the branch
* Read the readme and release to verify if they are accurate with the new strategy
Story details: https://app.shortcut.com/particle/story/126682/update-readme-for-cli
=> update readme with new pkg structure

npm-shrinkwrap.json, package.json, src/lib/flash-helper.test.js, src/lib/utilities.test.js
As title says.
https://github.com/particle-iot-inc/device-constants/pull/38
=> Support mono builds for rtk platforms and modify platform names

src/cli/publish.js, src/cli/publish.test.js, src/cmd/api.js, src/cmd/publish.js, src/lib/api-client.js, test/e2e/publish.e2e.js
Particle publishes are now default to private events. This update removes `--private` and `--public` args.
=> Remove `--private` and `--public` args from `publish`

npm-shrinkwrap.json, package.json, src/cli/usb.js, src/cli/usb.test.js, src/cmd/usb.js, src/cmd/usb.test.js, test/e2e/help.e2e.js, test/e2e/usb.e2e.js
Implements a command which resembles the linux `ifconfig` command that shows information about the network interfaces and their states
This is only possible on Gen2 because the USB control requests to request this information are guarded by `HAL_PLATFORM_IFAPI` which is enabled only for Gen3 and above.
Check out this branch and from the particle-cli root directory, run `npm start -- usb network-interfaces`
1. Connect a single device
2. Or Connect muitple devices
https://github.com/particle-iot/particle-usb/pull/102
=> Get network configuration of a device

src/cmd/serial.js
Run serial wifi configuration via control requests for gen3 and above. Use serial commands for gen2.
1. Setup this branch
2. Connect a single or multiple devices
3. Run the following commands
`npm start -- serial wifi`
`npm start -- serial wifi --file creds.json`
where creds.json looks like
```
{
"network": "my_ssid",
"security": "WPA2_AES",
"password": "my_password"
}
```
=> Fix wifi configuration on serial

src/app/cli.js
Story details: https://app.shortcut.com/particle/story/122790
In case a multi-word command doesn't exist but one of the words exist like `particle tokens list`, the command processor would return no command and no error so the output would be blank. With this simple fix, it will say `No such command 'tokens list'` but show the help for `particle list`. It's not a perfect fix, but it's better than the current situation.
=> fix: [sc-122790] Invalid commands are not failing properly

src/cmd/flash.js, src/cmd/update.js, src/lib/flash-helper.js, src/lib/flash-helper.test.js
Prevent downgrading Device OS below a minimum version of 6.0.0 for Protected Devices.
1. Put a Protected Device in Service Mode
2. The following commands should give the error "Cannot downgrade Device OS below version 6.0.0 on a Protected Device"
* `particle update --target 5.8.0`
* `particle flash --usb argon-system-part1@5.8.0.bin`
* `particle flash --local argon-system-part1@5.8.0.bin`
* `particle flash --local --target 5.8.0`
[Story](https://app.shortcut.com/particle/story/129083/when-flashing-device-os-modules-to-a-protected-device-reject-flashing-versions-older-than-the-minimum)
=> Feature/sc 129083/when flashing device os modules to a protected

src/cli/device-protection.js, src/cmd/device-protection.js, src/cmd/device-protection.test.js, test/e2e/device-protection.e2e.js
Reorder the E2E tests for device protection to account for the removal of disabling protection locally.
=> Rework device protection e2e tests

npm-shrinkwrap.json, package.json, src/cmd/device-protection.js, src/cmd/device-protection.test.js, src/cmd/device-util.js, src/cmd/usb-util.js, src/lib/device-protection-helper.js, src/lib/flash-helper.js, test/README.md
This is the base PR.
This PR adds a helper module `device-protection-helper.js` that can be used by multiple modules and prevent circular dependency issues. It also adds a new method that checks if a device is ready for use (ie rebooted after a certain reset operation was done)
See this [test plan](https://www.notion.so/particle/Test-Plan-for-CLI-commands-Protected-Open-23954df3eff94cad9b3002722f926fa9)
=> Put a Protected Device automatically in Service Mode to run CLI commands

src/cmd/usb-util.js
See - https://github.com/particle-iot/particle-cli/pull/753
See - https://github.com/particle-iot/particle-cli/pull/754
Simplify the generic wrapper that takes care of Protected Devices.
1. Skips checking Device Protection for gen2 devices (both dfu and normal modes)
2. A Protected Device is put into Service Mode to run a CLI operation and after that CLI command execution finishes (either success/error), we expect the device to be ready to take a control request to turn off Service Mode. It's the responsibility of the module (usb, serial, flash, etc...) to exit the CLI command execution with a device that is able to take control requests in normal mode (or simply be ready in dfu mode)
Unfortunately, this is a stand alone PR. 
Since usb module already uses this helper, run any `particle …
=> Simplify the generic helper that takes care of Protected Devices

src/cmd/wifi.js, src/cmd/wifi.test.js, test/e2e/usb.e2e.js, test/e2e/wifi-protected.e2e.js
Support Protected Devices while running `particle wifi xxx` commands
Run `particle wifi xxx` commands on Open Devices and Protected Devices, all platforms, all device-os versions
https://app.shortcut.com/particle/story/129842/automate-protected-devices-to-run-particle-wifi-commands
https://app.shortcut.com/particle/story/129841/automate-protected-devices-to-run-particle-wifi-commands-e2e-tests
=> Automate Protected Devices to run `particle wifi` commands

src/cmd/serial.js, src/cmd/serial.test.js, test/e2e/serial-protected.e2e.js
Support Protected Devices while running `particle serial xxx` commands
Run `particle serial xxx` commands on your Protected Devices as well as Open Devices
https://app.shortcut.com/particle/story/129645/automate-protected-devices-to-run-particle-serial-commands
https://app.shortcut.com/particle/story/129646/automate-protected-devices-to-run-particle-serial-commands-e2e-tests
=> Automate Protected Devices to run `particle serial` commands

src/cmd/flash.js, src/cmd/update.js, src/cmd/usb-util.js, src/lib/flash-helper.js, src/lib/flash-helper.test.js
This is only applicable for device-os 6.1.1 and lower.
The flashing operation is a multi-step process where each step obtains the device handle, sets the device to the appropriate mode (normal or DFU) based on the binary type, and then flashes the binary onto the device.
Currently, a generic wrapper is used to manage Protected Devices, placing the device in Service Mode only once at the beginning of the flashing process. However, this approach has a limitation: the devices on 6.1.0 and 6.0.0 exit Service Mode and return to a Protected state after flashing the bootloader. You could think of starting in DFU mode, but these device-os versions don't work well on Protected Devices in DFU mode.
The PR throws a downgrade error on Protected Devices if downgrading device-os from 6.1.1 to either …
=> Handle multi-step flashing on Protected Devices

src/cli/device-protection.js, src/cli/device-protection.test.js, src/cmd/device-protection.js
As title says. The option is `-d` to select device ID or name.
1. Connect multiple devices and verify that they are readable using `particle usb list`
2. Run `particle device-protection status -d device-id-or-name`
3. Run `particle device-protection disable -d device-id-or-name`
4. Run `particle device-protection enable -d device-id-or-name`
```
$ particle.js usb list
armadillo_cheetah [e00fce68623fcff480e85e47] (Boron)
power_robot [0a10aced202194944a04af80] (M-SoM, PROTECTED)
$ particle.js device-protection status -d 0a10aced202194944a04af80
[0a10aced202194944a04af80] (Product 28400): Protected Device
Run particle device-protection disable to put the device in Service Mode.
$
```
https://app.shortcut.com/particle/story/129867/specify-device-by-id-in-device-protection-commands
=> Add option to filter device with `particle device-protection` commands

src/cmd/product.js
As title says.
The `api-service` provides a list of device identifiers called `protectedDeviceIds`. This list includes the IDs of protected devices that are being attempted to be added to non-protected products. These device IDs have already been filtered out by the `api-service` to prevent them from being added to the product. In `particle-cli`, we notify the user that these device IDs are being skipped.
Refer to the testing instructions here - https://github.com/particle-iot-inc/api-service/pull/1564
https://github.com/particle-iot-inc/api-service/pull/1564
https://app.shortcut.com/particle/story/129604/don-t-allow-moving-a-protected-device-to-a-non-protected-product
=> Skip adding protected devices to non-protection products

npm-shrinkwrap.json, package.json, src/cmd/api.js, src/cmd/cloud.js
Story details: https://app.shortcut.com/particle/story/129513
=> Use the DeviceOS versions endpoints when compiling

src/cmd/binary.js, test/e2e/binary.e2e.js, test/e2e/serial-protected.e2e.js, test/e2e/update-protected.e2e.js, test/e2e/wifi-protected.e2e.js
Story details: https://app.shortcut.com/particle/story/130894
To help compare firmware running on a device from `particle serial inspect` with a firmware binary, it's helpful to have `particle binary inspect` output the UUID (app hash).
Steps to test:
```
particle binary inspect tracker-edge-19@3.3.0.bin
tracker-edge-19@3.3.0.bin
CRC is ok (2356f30a)
Compiled for tracker
This is an application module number 2 at version 6
It has a UUID of fb333f913ca62afdb67b9bc95ac335f9ebfb9e7e00f50525aef7bf22135df48e
It is firmware for product id 26 at version 19
It depends on a system module number 1 at version 3301
```
Also include assets in output from .bin (i.e not a bundle) to see if a binary includes assets.
```
particle binary inspect argon_firmware_1728490941405.bin …
```
=> feat: [sc-130894] Include UUID (app hash) in particle binary inspect

src/cmd/api.js, src/lib/api-client.js
Remove unused `listBuildTargets` in favor of `listDeviceOsVersions`
Both: `getBuildTargets` and `listBuildTargets` are not being used in `particle-cli` so we can remove them
Story details: https://app.shortcut.com/particle/story/131530/inspect-build-targets-from-api-service-and-create-a-plan-to-remove-old-flags
=> remove buildTargets list and get since is not being used in the code

src/cmd/api.js, src/cmd/setup-tachyon.js, src/lib/ui/index.js
Fix: 
* ssh key discrepancy naming
* camel case / snake case naming convention on some variables
* Add create product function
* Add silent mode to flash function in order to prevent confirmation messages
Story details: https://app.shortcut.com/particle/stories/space/74403/owned-by-me
=> Feature/sc 133607/tachyon setup issues

src/cmd/setup-tachyon.js
* Fix the way setup handle passwords that comes from a config file.
* Fix wifi password setting given that currently is returning undefined instead the actual data.
1. Pull down the branch: `git pull && git checkout bug/sc-133701/tachyon-setup-is-rehashing-an-already-hashed`
2. Attempt to setup a tachyon and save the config: `npm start -- tachyon setup --save_config my_config.cfg`
3. Attempt to setup again the tachyon but using the previously saved config (save it again): `npm start -- tachyon setup --load_config my_config.cfg --save_config my_new_config.cfg`
**outcome**
* wifi password should be stored in the config
* on the second attempt the system password should be match with the first file.
Story details: https://app.shortcut.com/particle/story/133701
=> Bug/sc 133701/tachyon setup is rehashing an already hashed

src/cli/tachyon.js, src/cmd/setup-tachyon.js
Add flag region to be used in tachyon setup.
Region can be stored and read it from the config file.
1. Pull down the branch: `git pull && git checkout feature/sc-133755/add-region-as-setup-option-by-default-use`
2. Attempt to setup a RoW region `npm start -- tachyon setup --region RoW`
3. Attempt to setup a NA (default)  `npm start -- tachyon setup`
4. Attempt to setup and save the config file `npm start -- tachyon setup --save_config test_region.cfg`
**outcome**
* If you pick `RoW` the binary that will be flashed should be `RoW`
* If you don't pick a region, then it will download `NA` by default
* In the config file you'll see a new element named `region`
* In case you don't pass a region as flag it will ask you to pick one.
Story details: https://app.shortcut.com/particle/story/133755
=> add region flag in case is not passed use NA

installer/unix/install-cli
I was getting a nearly blank `~/.bash_profile` on Tachyon when installing the CLI. This makes sure the add to path doesn't create new files.
=> Don't create a new shell config file when adding to path

src/cli/tachyon.js, src/cmd/download-tachyon-package.js, src/cmd/setup-tachyon.js
Add `--board` flag in setup command by default `formfactor`
* Attempt to run tachyon setup with variant flag: `npm start -- tachyon setup --board formfactor`
* Attempt to run tachyon setup with a nonexistent variant: `npm start --tachyon setup --board foo`
* Attempt to run tachyon setup without variant flag: `npm start --tachyon setup`
**outcome**
1. With an existent `board`, the download step will download the correct package
2. With a nonexistent `board`, the download step will fail with: `No builds available for the selected region, variant or board`
3. Without  a`board`, the download step will download the package with the headless variant
Story details: https://app.shortcut.com/particle/story/133923
=> add board option for tachyon setup and download command

src/cmd/setup-tachyon.js
* apiServer is based on the configured api URL in your particle config
* server is the websocket server, set based on whether "staging" is in the api URL above
* verbose logging in particle-linux is set to true if we are in staging
=> Add apiServer, server, and verbose to tachyon bootstrap config flash

src/cli/flash.js, src/cmd/flash.js
Add a new flag to prevent the device boot after flash is completed
Story details: https://app.shortcut.com/particle/story/134175/prevent-device-boot-after-flashing-in-flash-firmware-station
=> add skip-reset flag to prevent the device boot after flashing

.eslintrc.js, src/app/cli.js, src/app/update-check.js, src/app/update-check.test.js, src/cmd/esim.js, src/cmd/setup-tachyon.js, src/cmd/update-cli.js
Running `particle update-cli` can trigger a background run of `particle update-cli` which leads to a race condition between the 2 update processes.
Rework the background update check to skip an update when running `particle update-cli`.
=> Avoid background update when running update-cli

src/cmd/esim.js
Fix issues when:
The device has already an enabled profile (don't fail)
The EID mismatch with the expected by the esim vendor (the profile is already attached to a device) -> Fail but remove the profile from cache
I was able to test just the enabled profile.
Device led stuck in red
Devices led is green
Story details: 
https://app.shortcut.com/particle/story/134368/fix-enable-profile-logic-when-profile-is-already-active
https://app.shortcut.com/particle/story/134369/handle-eid-mismatch-during-download-profile-step
=> add esim profiles as used in cache if they have an eid mismatch

src/cmd/identify-tachyon.js, src/lib/tachyon-utils.js
Change modem data to Manufacturing data since is more accurate.
* Run tachyon identify command: `npm start -- tachyon identify`
**outcome**
Should return the tachyon info with `Manufacturing data` "Found" or "Missing" depending the case, e.g: 
```
Device ID: 422a060000000000f70d57f7
Region: NA
Manufacturing data: Found
OS Version: Ubuntu 20.04 EVT
```
=> change modem data identify property in favor of manufacturing data

src/cmd/api.js, src/cmd/setup-tachyon.js
Send deviceId when registering a new linux device. That will be required to get data to connect with the cloud
* Attempt to setup a tachyon device
https://app.shortcut.com/particle/story/134502/change-cli-tachyon-setup-for-esim-implementation
=> add deviceId to registration code

.github/workflows/reusable-build.yml, src/cmd/download-tachyon-package.js, src/cmd/setup-tachyon.js
* Add `dvt` as default for download-package command
* Print out OS information on tachyon setup (that would help to debug in case of issues)
* Update sign artifact to use always the latest.
* Try to download a tachyon OS by using `tachyon download-package` command
* Set up your tachyon device
**outcome**
`download-package` command
* By default dvt board will be settled
* You'll be able to pick a variant (desktop/headless) according your board
`tachyon setup` command
* On download step you'll see the OS information that is about to be installed in your device e.g. 👇
=> make dvt default on download, ask for variant and fix rb3 download

src/cmd/setup-tachyon.js, src/lib/download-manager.js, src/lib/download-manager.test.js
Allow to retry after checksum failure. Confirm with the users if they want to remove the unmatched file or remove it manually.
In case of manual removal it will throw checksum mismatch error.
* Copy an old version of a OS with the name of the stable OS version: `cp tachyon-ubuntu-20.04-NA-desktop-formfactor_dvt-1.0.159.zip tachyon-ubuntu-20.04-NA-desktop-formfactor_dvt-1.0.161.zip`
* Attempt to setup your device with the stable version
**outcome**
* since you are using a different OS, the checksum should fail. 
* It will ask you to remove the wrong file and retry
* In case you hit 'N' it will finish the setup with an error in other case it will remove the file and redownload it again
Story details: https://app.shortcut.com/particle/story/135100/don-t-delete-the-file-in-case-doesn-t-match-a …
=> Feature/sc 135100/don t delete the file in case doesn t match and

npm-shrinkwrap.json, package.json, src/app/command-processor.test.js, src/cli/library_init.test.js, src/cli/library_install.test.js, src/cli/library_migrate.test.js, src/cmd/binary.js, src/lib/api-client.js, src/lib/utilities.js, test/integration/command-processor.integration.js, test/integration/library.integration.js, test/integration/library_init.integration.js, test/integration/library_install.integration.js
#245 Changed the license to Apache 2.0 but left some comment headers with the previous LGPL language.
This PR completes the intent of #245 that the LICENSE file at the top of the repo should define the text of the license for all the files in the repo rather than some files having separate license headers.
=> Rely on the LICENSE text at the top of the repo rather than license headers

assets/qdl/read_gpt.xml, src/cmd/setup-tachyon.js, src/lib/tachyon-utils.js
Story details: https://app.shortcut.com/particle/story/135893
We'll determine whether a Tachyon device is running Ubuntu 20.04 or 24.04 based on the start of the boot_a or boot_b partition.
Also changes the default board to DVT.
This requires reading the GPT from the 6 LUN. This may fail for EVT devices so try to catch the error when reading the GPT files. If qdl reading fails for another reason than `TachyonConnectionError`, the operation will continue. If it's due to the GPT 6 being missing on EVT, the missing file will be ignored. Otherwise the error will be reported as Failed to parse partition table ${i} from device.
Steps to test:
=> feat: [sc-135893] Detect Ubuntu 20.04 or 24.04
